### ISSUE TITLE
OS Error when using Python on Intel Mac OS 

### ISSUE THREAD

**Issue by andrealati** [ORNL/TASMANIAN#777]
Hi, 

I've been trying to install v8.0 on my Intel Mac OS. I've installed using `cmake` but the `make test_install` raises some failed test on Python and when I try to add the modules in Python I get the following OS Error
`OSError: dlopen(/usr/local/lib/libtasmaniancaddons.dylib, 0x0006): weak-def symbol not found '__ZN7TasGrid20TasmanianDenseSolver18solvesLeastSquaresINSt3__17complexIdEEEEvPKNS_19AccelerationContextEiiPT_iS9_'`

I've added the full traceback as well the installation steps below. I'd be grateful for any advice on how to fix this. 
Thank you very much for your help. 
Andrea

```
Python 3.11.8 (main, Feb 26 2024, 15:43:17) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append("/usr/local/share/Tasmanian/python")
>>> import Tasmanian
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/share/Tasmanian/python/Tasmanian.py", line 46, in <module>
    from TasmanianAddons import *
  File "/usr/local/share/Tasmanian/python/TasmanianAddons.py", line 39, in <module>
    pLibCTSG = cdll.LoadLibrary(TasmanianConfig.__path_libcaddons__)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andreaalati/opt/anaconda3/envs/py311/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/andreaalati/opt/anaconda3/envs/py311/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/usr/local/lib/libtasmaniancaddons.dylib, 0x0006): weak-def symbol not found '__ZN7TasGrid20TasmanianDenseSolver18solvesLeastSquaresINSt3__17complexIdEEEEvPKNS_19AccelerationContextEiiPT_iS9_'
```

Installation 
```
cmake  -D Tasmanian_ENABLE_PYTHON=ON ../TASMANIAN-8.0 
make 
make install 
make test_install 
```

after `make test_install` I get 
```
Running tests...
Test project /Users/andreaalati/Documents/tasmanian/Build/tasmanian_test_install
    Start 1: SparseGrids
1/6 Test #1: SparseGrids ......................   Passed    9.02 sec
    Start 2: DREAM
2/6 Test #2: DREAM ............................   Passed    9.14 sec
    Start 3: Optimization
3/6 Test #3: Optimization .....................   Passed    0.30 sec
    Start 4: Python::SparseGrids
4/6 Test #4: Python::SparseGrids ..............***Failed    2.20 sec
    Start 5: Python::DREAM
5/6 Test #5: Python::DREAM ....................***Failed    1.27 sec
    Start 6: Python::Optimization
6/6 Test #6: Python::Optimization .............***Failed    1.24 sec

50% tests passed, 3 tests failed out of 6

Total Test time (real) =  23.18 sec

The following tests FAILED:
	  4 - Python::SparseGrids (Failed)
	  5 - Python::DREAM (Failed)
	  6 - Python::Optimization (Failed)
Errors while running CTest
```

**Comment by mkstoyanov** [comment]
Hi,

you're saying "Intel OSX" but the error that you're getting is the same as what we were getting under the M-chips. The core issue is that loading libraries under Python using the default settings will not make the symbols available to follow-on loaded libraries. It seems that Apple has adopted this as a strategy across the CPUs.

Try the tagged issue workaround
```
    python -m pip install Tasmanian==8.1b2 --user
```

Or simply try to build from the latest master branch.

**Comment by andrealati** [comment]
Thanks a lot for the super prompt reply - this solves it
